platform :ios, '8.0'
use_frameworks!

target :MCDiary do
  pod 'ReactiveCocoa'
  pod 'CocoaLumberjack', :inhibit_warnings => true
  pod 'HexColors'
  pod 'Masonry'
  pod 'AVOSCloudDynamic'
  pod 'AVOSCloudIMDynamic'
  pod 'AVOSCloudCrashReportingDynamic'
  pod 'RegExCategories'
  pod 'RSKImageCropper'
  pod 'SVProgressHUD'
  pod 'DLRadioButton'
  pod 'DateTools'
  pod 'TPKeyboardAvoiding'
  pod 'MMDrawerController'
end

target :MCDiaryKit do
  pod 'ReactiveCocoa'
  pod 'CocoaLumberjack', :inhibit_warnings => true
  pod 'HexColors'
  pod 'Masonry'
  pod 'RegExCategories'
  pod 'DLRadioButton'
end




