platform :ios, '8.0'
use_frameworks!

pod 'ReactiveCocoa', '2.5'
pod 'CocoaLumberjack', :inhibit_warnings => true
pod 'HexColors'
pod 'Masonry'
pod 'RegExCategories'
pod 'RSKImageCropper'
pod 'SVProgressHUD'
pod 'DLRadioButton'
pod 'DateTools'
pod 'TPKeyboardAvoiding'
pod 'MMDrawerController'
pod 'AVOSCloud'
pod 'Fabric'
pod 'Crashlytics'


